use super::{context_relative, intrinsic_track_sizing};

/// The filed defect. The value carries `var()`, so the gate consults this predicate, and the
/// only thing separating the two is the unit — one recognised, one not.
#[test]
fn a_viewport_length_is_fluid_exactly_as_a_percentage_is() {
    assert!(context_relative("calc(var(--gutter) + 30vw)"));
    assert!(context_relative("calc(var(--gutter) + 30%)"));
}

/// Viewport units are generated by a naming rule, so every member the rule produces must be
/// recognised. Listing today's units would leave the next one to re-arm the same defect.
#[test]
fn every_unit_the_viewport_naming_rule_produces_is_recognised() {
    for axis in ["w", "h", "i", "b", "min", "max"] {
        for prefix in ["", "s", "l", "d"] {
            let value = format!("calc(var(--gutter) + 30{prefix}v{axis})");
            assert!(context_relative(&value), "{value} is viewport-relative");
        }
    }
}

/// A container-query length resolves to pixels and recomputes when its container resizes,
/// exactly as a viewport length does, and the capture proved it freezes the same way.
#[test]
fn a_container_query_length_is_fluid_for_the_same_reason() {
    assert!(context_relative("calc(var(--gutter) + 30cqw)"));
    assert!(context_relative("calc(var(--gutter) + 30cqmin)"));
}

/// The gate exists to prefer the sample for values that do not move. Answering yes to
/// everything carrying `var()` would disable it rather than correct it.
#[test]
fn a_value_that_resolves_to_the_same_length_at_any_width_is_not_fluid() {
    assert!(!context_relative("calc(var(--gutter) + 4px)"));
    assert!(!context_relative("var(--brand)"));
    assert!(!context_relative("calc(var(--gutter) + 2rem)"));
}

/// The over-match a substring repair would introduce. A custom property named like a unit
/// spells the letters without being a dimension.
#[test]
fn a_custom_property_named_like_a_unit_is_not_fluid() {
    assert!(!context_relative("calc(var(--vwrap) + 40px)"));
    assert!(!context_relative("var(--vh-offset)"));
    assert!(!context_relative("url(a%20b.png)"));
}

/// A unit whose letters merely begin like a viewport unit must not match; the axis has to be
/// the whole of what follows the prefix.
#[test]
fn a_unit_that_only_starts_like_a_viewport_unit_is_not_fluid() {
    assert!(!context_relative("30vwide"));
    assert!(!context_relative("30cqwide"));
    assert!(!context_relative("30dvhx"));
}

/// Track lists respond to width by changing their column count rather than by carrying a
/// unit, so that reason to keep authored text is separate and must survive unchanged.
#[test]
fn an_intrinsically_sized_track_list_is_kept_for_its_own_reason() {
    let tracks = "repeat(auto-fit, minmax(min(var(--min-col), 100%), 1fr))";
    assert!(intrinsic_track_sizing(tracks));
    assert!(!intrinsic_track_sizing("calc(var(--gutter) + 30vw)"));
    assert!(intrinsic_track_sizing("clamp(60px, 12.5vw, 200px)"));
}
