use super::css_scan;

/// Whether an authored value must be kept as text rather than answered by the sample.
///
/// An authored value that references a custom property is normally dropped in favour of the
/// sampled computed value, which is safe for a colour or a spacing but destroys layout that
/// responds to something the recreation never re-measures. The two reasons that can rescue
/// such a value are asked separately below because they are different questions: whether a
/// length tracks a layout context is a question about units, which only a tokenizer can
/// answer, while whether a track list sizes itself from the available space is a question
/// about function and keyword names. Flattening both into one substring scan is what left the
/// units out, since no substring test can name a unit without also matching `--vwrap`.
pub(super) fn fluid(value: &str) -> bool {
    context_relative(value) || intrinsic_track_sizing(value)
}

/// Whether a value's used value is a function of a layout context the recreation never
/// re-measures, so sampling it once records a constant where the page had a function.
///
/// The capture reads resolved values, and CSSOM resolves a viewport length to the pixels it
/// spans at the moment it was read. A sampled `30vw` is therefore right at the width it was
/// measured at and wrong at every other width, and no later stage can recover the authored
/// unit from the pixel. Such a value has to be kept as authored text; a value that resolves
/// to the same pixels at any width is better taken from the sample, which is why this asks a
/// question rather than always answering yes.
///
/// The question is asked of parsed tokens, not of substrings. A unit only means a unit when
/// it follows a number: `--vwrap`, a font named `Vwide` and a `url(a%20b.png)` path all spell
/// unit letters without being dimensions, so a `contains` test cannot hold a unit at all —
/// which is why the list this replaced held function names and keywords but no unit, and lost
/// every viewport length as a result.
fn context_relative(value: &str) -> bool {
    css_scan::units(value)
        .into_iter()
        .any(context_relative_unit)
}

/// Whether a unit resolves against something outside the element's own box.
///
/// Viewport units are generated by a naming rule rather than enumerated — an optional small,
/// large or dynamic prefix, then `v`, then the axis — so the rule is spelled out here instead
/// of listing the twenty-four members it produces. Listing them would still be a list, and
/// would still go stale against the next prefix the specification adds.
///
/// Container-query units are the same mechanism with a query container in place of the
/// viewport: also resolved to pixels by CSSOM, also recomputed when their reference resizes.
/// A percentage resolves against the containing block, which moves for the same reason.
fn context_relative_unit(unit: &str) -> bool {
    if unit == "%" {
        return true;
    }
    let axis = unit
        .strip_prefix("cq")
        .or_else(|| viewport_axis(unit))
        .unwrap_or_default();
    matches!(axis, "w" | "h" | "i" | "b" | "min" | "max")
}

/// The axis of a viewport unit, after its optional small, large or dynamic prefix.
fn viewport_axis(unit: &str) -> Option<&str> {
    let unit = unit.strip_prefix(['s', 'l', 'd']).unwrap_or(unit);
    unit.strip_prefix('v')
}

/// Whether a value sizes a track list from the space available rather than from a length.
///
/// This is a second, unrelated reason to keep authored text: `repeat(auto-fit, ...)` changes
/// the number of columns with the width, so a sample records the count the capture happened
/// to produce. These really are function and keyword names, so naming them is correct here in
/// a way it never was for a unit.
fn intrinsic_track_sizing(value: &str) -> bool {
    ["repeat(", "minmax(", "auto-fit", "auto-fill", "clamp("]
        .into_iter()
        .any(|token| value.contains(token))
}

#[cfg(test)]
#[path = "fluid_value_tests.rs"]
mod fluid_value_tests;
