export const figmaGuid = (value) =>
  value ? `${value.sessionID}:${value.localID}` : null;

const keep = (value) => value == null ? undefined : value;

export function compactFigmaNode(node, reference, geometry, vectorNetwork) {
  return {
    id: figmaGuid(node.guid),
    parentId: figmaGuid(node.parentIndex?.guid),
    type: node.type,
    name: node.name,
    visible: keep(node.visible),
    locked: keep(node.locked),
    opacity: keep(node.opacity),
    blendMode: keep(node.blendMode),
    size: keep(node.size),
    minSize: keep(node.minSize),
    maxSize: keep(node.maxSize),
    transform: keep(node.transform),
    horizontalConstraint: keep(node.horizontalConstraint),
    verticalConstraint: keep(node.verticalConstraint),
    proportionsConstrained: keep(node.proportionsConstrained),
    frameMaskDisabled: keep(node.frameMaskDisabled),
    stackMode: keep(node.stackMode),
    stackWrap: keep(node.stackWrap),
    stackSpacing: keep(node.stackSpacing),
    stackCounterSpacing: keep(node.stackCounterSpacing),
    stackPrimaryAlignItems: keep(node.stackPrimaryAlignItems),
    stackCounterAlignItems: keep(node.stackCounterAlignItems),
    stackPrimarySizing: keep(node.stackPrimarySizing),
    stackCounterSizing: keep(node.stackCounterSizing),
    stackChildAlignSelf: keep(node.stackChildAlignSelf),
    stackChildPrimaryGrow: keep(node.stackChildPrimaryGrow),
    stackPositioning: keep(node.stackPositioning),
    stackReverseZIndex: keep(node.stackReverseZIndex),
    stackPaddingRight: keep(node.stackPaddingRight),
    stackPaddingBottom: keep(node.stackPaddingBottom),
    stackVerticalPadding: keep(node.stackVerticalPadding),
    stackHorizontalPadding: keep(node.stackHorizontalPadding),
    fills: reference(node.fillPaints),
    backgrounds: reference(node.backgroundPaints),
    strokes: reference(node.strokePaints),
    strokeWeight: keep(node.strokeWeight),
    strokeAlign: keep(node.strokeAlign),
    strokeJoin: keep(node.strokeJoin),
    strokeCap: keep(node.strokeCap),
    dashPattern: reference(node.dashPattern),
    bordersTakeSpace: keep(node.bordersTakeSpace),
    borderTopWeight: keep(node.borderTopWeight),
    borderRightWeight: keep(node.borderRightWeight),
    borderBottomWeight: keep(node.borderBottomWeight),
    borderLeftWeight: keep(node.borderLeftWeight),
    effects: reference(node.effects),
    cornerRadius: keep(node.cornerRadius),
    cornerSmoothing: keep(node.cornerSmoothing),
    cornerRadii: [
      node.rectangleTopLeftCornerRadius,
      node.rectangleTopRightCornerRadius,
      node.rectangleBottomRightCornerRadius,
      node.rectangleBottomLeftCornerRadius,
    ].some((value) => value != null)
      ? [
          node.rectangleTopLeftCornerRadius,
          node.rectangleTopRightCornerRadius,
          node.rectangleBottomRightCornerRadius,
          node.rectangleBottomLeftCornerRadius,
        ]
      : undefined,
    arcData: keep(node.arcData),
    booleanOperation: keep(node.booleanOperation),
    starInnerScale: keep(node.starInnerScale),
    text: keep(node.textData?.characters),
    fontName: keep(node.fontName),
    fontSize: keep(node.fontSize),
    fontWeight: keep(node.fontWeight),
    fontVariations: reference(node.fontVariations),
    lineHeight: keep(node.lineHeight),
    letterSpacing: keep(node.letterSpacing),
    textAlignHorizontal: keep(node.textAlignHorizontal),
    textAlignVertical: keep(node.textAlignVertical),
    textAutoResize: keep(node.textAutoResize),
    textTruncation: keep(node.textTruncation),
    maxLines: keep(node.maxLines),
    textCase: keep(node.textCase),
    textDecoration: keep(node.textDecoration),
    hyperlink: keep(node.hyperlink),
    fillGeometry: reference(geometry(node.fillGeometry)),
    strokeGeometry: reference(geometry(node.strokeGeometry)),
    vectorData: reference(node.vectorData),
    vectorNetwork: reference(vectorNetwork(node)),
    layoutGrids: reference(node.layoutGrids),
    gridRows: reference(node.gridRows),
    gridColumns: reference(node.gridColumns),
    gridRowGap: keep(node.gridRowGap),
    gridColumnGap: keep(node.gridColumnGap),
    gridRowAnchor: keep(node.gridRowAnchor),
    gridColumnAnchor: keep(node.gridColumnAnchor),
    gridChildHorizontalAlign: keep(node.gridChildHorizontalAlign),
    gridChildVerticalAlign: keep(node.gridChildVerticalAlign),
    styleIds: {
      fill: keep(node.styleIdForFill),
      stroke: keep(node.styleIdForStrokeFill),
      text: keep(node.styleIdForText),
      effect: keep(node.styleIdForEffect),
      grid: keep(node.styleIdForGrid),
    },
    symbolData: reference(node.symbolData),
    derivedSymbolData: reference(node.derivedSymbolData),
    componentPropRefs: reference(node.componentPropRefs),
    componentPropDefs: reference(node.componentPropDefs),
    componentPropAssignments: reference(node.componentPropAssignments),
    variantPropSpecs: reference(node.variantPropSpecs),
    parameterConsumptionMap: reference(node.parameterConsumptionMap),
    interactions: node.prototypeInteractions?.length
      ? reference(node.prototypeInteractions)
      : undefined,
    transitionType: keep(node.transitionType),
    scrollDirection: keep(node.scrollDirection),
    scrollBehavior: keep(node.scrollBehavior),
    variableSetId: keep(node.variableSetID),
    variableType: keep(node.variableResolvedType),
    variableValues: reference(node.variableDataValues),
    variableModes: reference(node.variableSetModes),
    variableModeBySet: reference(node.variableModeBySetMap),
    variableConsumptionMap: reference(node.variableConsumptionMap),
    exportSettings: reference(node.exportSettings),
  };
}
